In [4]:
from scipy import signal
import numpy as np

In [6]:
w0 = 2*np.pi*5
num = w0
den = [1, w0]
lowpass = signal.TransferFunction(num, den)

In [7]:
print(lowpass)

TransferFunctionContinuous(
array([31.41592654]),
array([ 1.        , 31.41592654]),
dt: None
)


In [11]:
dt = 1.0/1.0 #sampling frequency of 1kHz
discreteLowPass = lowpass.to_discrete(dt, method='gbt', alpha = 0.5)

In [12]:
print(discreteLowPass)

TransferFunctionDiscrete(
array([0.9401483, 0.9401483]),
array([1.       , 0.8802966]),
dt: 1.0
)


In [13]:
b = discreteLowPass.num
a = -discreteLowPass.den
print("Filter coefficients b_i" + str(b))
print("Filter coefficients a_i" + str(a[1:]))

Filter coefficients b_i[0.9401483 0.9401483]
Filter coefficients a_i[-0.8802966]
