In [4]:
from scipy import signal
import numpy as np

In [6]:
w0 = 2*np.pi*5
num = w0
den = [1, w0]
lowpass = signal.TransferFunction(num, den)

In [7]:
print(lowpass)

TransferFunctionContinuous(
array([31.41592654]),
array([ 1.        , 31.41592654]),
dt: None
)


In [8]:
dt = 1.0/1000.0 #sampling frequency of 1kHz
discreteLowPass = lowpass.to_discrete(dt, method='gbt', alpha = 0.5)

In [9]:
print(discreteLowPass)

TransferFunctionDiscrete(
array([0.01546504, 0.01546504]),
array([ 1.        , -0.96906992]),
dt: 0.001
)


In [ ]:
b = discreteLowPass.num
a = -discreteLowPass.den
print("Filter coefficients b_i" + str(b))
print("Filter